export const clubs: string[] = [
	"STEM",
	"Humanities and Social Sciences",
	"Professional Studies",
	"Arts and Design",
	"Environmental and Agricultural Sciences",
	"Creative and Performing Arts",
	"Sports and Recreation",
	"Spritual and Religious",
	"Social and Lifestyle",
	"Career Services and Networking",
	"Student Governance and Leadership",
	"Wellness and Mental Health",
	"Diversity and Inclusion",
]
